---
# 这个剧本在所有节点上运行

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 关闭selinux即时生效
  shell: setenforce 0

# SELINUX= can take one of these three values:
    #     enforcing - SELinux security policy is enforced.
    #     permissive - SELinux prints warnings instead of enforcing.
    #     disabled - No SELinux policy is loaded.

- name: 永久关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    # regexp: "SELINUX=(.*)"
    line: "SELINUX=disabled"

- name: 禁止swap即时生效
  # shell: sysctl vm.swappiness=1
  shell: swapoff -a

- name: 永久禁止swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts 

#- name: 同步系统时间
#  yum: name=ntpdate state=present
#- name: 同步系统时间
#  shell: ntpdate time.windows.com

